### ISSUE TITLE
ImportError on opening Anki

### ISSUE THREAD

**Issue by justremember** [hgiesel/anki_straight_reward#35]
![image](https://github.com/hgiesel/anki_straight_reward/assets/14817065/8a7a7832-a508-4379-a048-f68305ca309f)

Also, someone else had the exact same trouble
https://www.reddit.com/r/medicalschoolanki/comments/17kro2j/straight_rewards_addon_error/

**Comment by Reunion31** [comment]
Exact same issue here.

**Comment by working-name** [comment]
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Straight Reward⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/Users/username/Library/Application Support/Anki2/addons21/957961234/__init__.py", line 40, in <module>
    from .src import init
  File "/Users/username/Library/Application Support/Anki2/addons21/957961234/src/__init__.py", line 2, in <module>
    from .lib import init_review_hook, init_sync_hook
  File "/Users/username/Library/Application Support/Anki2/addons21/957961234/src/lib/__init__.py", line 1, in <module>
    from .review_hook import init_review_hook
  File "/Users/username/Library/Application Support/Anki2/addons21/957961234/src/lib/review_hook.py", line 9, in <module>
    from anki.scheduler.v3 import SetSchedulingStatesRequest
ImportError: cannot import name 'SetSchedulingStatesRequest' from 'anki.scheduler.v3' (unknown location)
⁩

**Comment by DiamondScythe** [comment]
Same issue. Can you revert the update please?

**Comment by hgiesel** [comment]
Can you all state your Anki versions please?

**Comment by Reunion31** [comment]
> Can you all state your Anki versions please?

2.1.61

**Comment by hgiesel** [comment]
I think I just fixed it. Please try it out

**Comment by Reunion31** [comment]
> I think I just fixed it. Please try it out

Seems to be working indeed! Thank you so much.

**Comment by talkael** [comment]
2.1.65 qt6 mac; still having an issue with editing the values keeps resetting and cant seem to access the old menu by holding shift

**Comment by hgiesel** [comment]
> 2.1.65 qt6 mac; still having an issue with editing the values keeps resetting and cant seem to access the old menu by holding shift

The new menu not working is an unrelated issue, PRs welcome
