### ISSUE TITLE
Doesn't work for anki version 23.10

### ISSUE THREAD

**Issue by lil5** [hgiesel/anki_straight_reward#36]
Add-on Startup Failed
The following add-ons failed to load: ⁨
[Straight Reward](https://ankiweb.net/shared/info/957961234)⁩
They may need to be updated to support this version of Anki. Click the Check for Updates button to see if any updates are available.
You can use the Copy Debug Info button to get information that you can paste in a report to the add-on author.
For add-ons that don't have an update available, you can disable or delete the add-on to prevent this message from appearing.

#### Anki Version:
```
Version ⁨23.10 (51a10f09)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
```

#### Debug Log:
```log
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-16 16:05:28

When loading Straight Reward:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/lil5/Library/Application Support/Anki2/addons21/957961234/__init__.py", line 40, in <module>
    from .src import init
  File "/Users/lil5/Library/Application Support/Anki2/addons21/957961234/src/__init__.py", line 2, in <module>
    from .lib import init_review_hook, init_sync_hook
  File "/Users/lil5/Library/Application Support/Anki2/addons21/957961234/src/lib/__init__.py", line 1, in <module>
    from .review_hook import init_review_hook
  File "/Users/lil5/Library/Application Support/Anki2/addons21/957961234/src/lib/review_hook.py", line 4, in <module>
    from aqt.gui_hooks import (
ImportError: cannot import name 'review_did_undo' from 'aqt.gui_hooks' (unknown location)

```

https://ankiweb.net/shared/info/957961234

**Comment by lil5** [comment]
Fixed here: #34 

But not it's not available yet on anki addons website.

I suggest keeping open until then for searchablity.

**Comment by btsworld613** [comment]
It's still not working for Anki 23.10 and I use Windows 11. Thank you!

**Comment by DoctorToBeIn23** [comment]
Loads now but not working and notification not popping up.

**Comment by shigeyukey** [comment]
Hmmm? The author seems to be very busy so I thought I would make a temporary Fork and upload it to AnkiWeb, but after reading the source code, this problem has already been fixed. So it should work without repair. Wouldn't this problem be solved by updating the add-on to the latest version?
